### PR TITLE
#94 create a new file system

### LINKED ISSUE #94: engine: literally create a new file system
The current file system does not support a lot of datasets. With my tests, it crashes shallow of 156k, because the design is flawed and cannot hold more than a few 100 megs of data.

Implement a new one.

### PR DESCRIPTION
**Pull request by tpdenk**
The new file system does not store data in a single file anymore.

### CODE REVIEW

File: internal/engine/dbfs/dbfs.go [hunk 1]
```diff
@@ -0,0 +1,179 @@
...
+// Table returns a Table object representing the files and directories
+// for the table with the given name, or an error if the table does not
+// exist. Call HasTable to see whether a table with a given name exists.
+func (dbfs *DBFS) Table(name string) (Table, error) {
+	infos, err := dbfs.loadTablesInfo()
+	if err != nil {
+		return Table{}, err
+	}
+
+	// perform checks
```
Comment (SUMUKHA-PK) [inline internal/engine/dbfs/dbfs.go:66]: What is this supposed to be?

File: internal/engine/page_container.go [hunk 2]
```diff
@@ -59,5 +60,5 @@ func (c PageContainer) Load() (*page.Page, error) {
 // Unload unpins the page of this container in the cache.
```
Comment (SUMUKHA-PK) [inline internal/engine/page_container.go:60]: Unpin out.

File: internal/engine/record.go [hunk 3]
```diff
@@ -8,6 +8,8 @@ import (
 	"github.com/xqueries/xdb/internal/engine/types"
 )
 
+var _ = serializeRow // FIXME: remove when InsertRow is implemented
```
Comment (SUMUKHA-PK) [inline internal/engine/record.go:11]: Maybe write about why this is being done so that we dont forget it.

File: internal/engine/table.go [hunk 4]
```diff
@@ -43,16 +41,9 @@ type Inserter interface {
...
-
-	tablePage PageContainer
-	dataPage  PageContainer
-
-	// application-facing fields
-
 	name         string
-	highestRowID uint32
-	cols         []table.Col
+	schema       *schema.Schema
```
Comment (SUMUKHA-PK) [inline internal/engine/table.go:45]: Is `schema` a right name for this? I understand that schema means any plan but in the future of this db being used by people I dont want someone to get lost thinking this is the DB schema.

File: internal/engine/table.go [hunk 5]
```diff
@@ -62,58 +53,30 @@ type Table struct {
 func (e Engine) LoadTable(name string) (table.Table, error) {
 	e.profiler.Enter("load table").Exit()
 
-	tablesPage, err := e.tablesPageContainer.Load()
+	tableMeta, err := e.dbfs.Table(name)
```
Comment (SUMUKHA-PK) [inline internal/engine/table.go:56]: `TableMeta` ? Isn't it the actual table?

File: internal/engine/table_iterator.go [hunk 6]
```diff
@@ -3,43 +3,71 @@ package engine
...
 	i.profiler.Enter("next row").Exit()
 
-	if i.slots == nil {
-		i.slots = i.dataPage.OccupiedSlots()
+	if len(i.pages) == 0 {
+		return table.Row{}, table.ErrEOT
 	}
-	if i.index >= len(i.slots) {
+
+start:
```
Comment (SUMUKHA-PK) [inline internal/engine/table_iterator.go:45]: Can you briefly explain the flow happening inside this label?

Comment (SUMUKHA-PK) [reply internal/engine/table_iterator.go:45]: Because there are many conditionals, those are best documented instead of thinking hard next time to figure out what and why it was done for :))

File: internal/test/examples_test.go [hunk 7]
```diff
@@ -101,18 +102,3 @@ func TestExample07(t *testing.T) {
 
 	t.Logf("profile:\n%v", p.Profile().String())
 }
-
-func TestExample08(t *testing.T) {
```
Comment (SUMUKHA-PK) [inline internal/test/examples_test.go:105]: Removed because of lack of support now?

**Review by SUMUKHA-PK — COMMENTED** [review]
Good start! Some questions and documentation needs are expressed. Maybe also add some sort of doc to the `xdbdoc` repo if this is concrete.

File: internal/engine/dbfs/dbfs.go [hunk 8]
```diff
@@ -0,0 +1,179 @@
...
+func (dbfs *DBFS) Close() error {
+	// nothing to do here yet
+	return nil
+}
+
+// Table returns a Table object representing the files and directories
+// for the table with the given name, or an error if the table does not
+// exist. Call HasTable to see whether a table with a given name exists.
+func (dbfs *DBFS) Table(name string) (Table, error) {
+	infos, err := dbfs.loadTablesInfo()
```
[the remark this answers is not in the document]
Comment (tsatke) [reply internal/engine/dbfs/dbfs.go:61]: probably better, yes

File: internal/engine/dbfs/dbfs.go [hunk 9]
```diff
@@ -0,0 +1,179 @@
...
+
+	_, ok := infos[name]
+	return ok, nil
+}
+
+// CreateTable creates empty table files for a table with the given name.
+// This will return an error if a table with the given name already exists.
+// Calling this method will also create an entry in the tables info file.
+func (dbfs *DBFS) CreateTable(name string) (Table, error) {
+	infos, err := dbfs.loadTablesInfo()
```
[the remark this answers is not in the document]
Comment (tsatke) [reply internal/engine/dbfs/dbfs.go:93]: not worth a separate function really, it's just a map access and checks.
I wanted to avoid a `func Table(name string) (Table, bool, error)`, since I really don't like bool and error returned for some reason. Probably because it requires more checks for the caller, which doesn't make calling code prettier.

File: internal/engine/dbfs/table.go [hunk 10]
```diff
@@ -0,0 +1,42 @@
...
+	"github.com/xqueries/xdb/internal/id"
+)
+
+// Table is a wrapper around the table directory of a specific table.
+type Table struct {
+	id id.ID
+	fs afero.Fs
+}
+
+// DataFile returns the data file of the table that this object represents.
```
[the remark this answers is not in the document]
Comment (tsatke) [reply internal/engine/dbfs/table.go:18]: The data file is a paged file, meaning it consists of multiple pages. If a table has too much data to fit on a single page, it will take up multiple pages, but all in this file.
Also, for better understanding (once that is proven to work, I'll upload a concept), this is the current structure.
```
+ /
| tables
| + tables.info // contains entries of the form myTable=someID
| + someID
| | + data
| | + schema
| + otherID
| | +data
| | + schema
```

File: internal/engine/engine.go [hunk 11]
```diff
@@ -85,29 +80,15 @@ func (e Engine) Evaluate(cmd command.Command) (table.Table, error) {
...
-	_, ok := tablesPage.Cell([]byte(name))
-	return ok
-}
-
-// Closed determines whether the underlying database file was closed. If so,
-// this engine is considered closed, as it can no longer operate on the
-// underlying file.
-func (e Engine) Closed() bool {
-	return e.dbFile.Closed()
+	ok, err := e.dbfs.HasTable(name)
```
[the remark this answers is not in the document]
Comment (tsatke) [reply internal/engine/engine.go:85]: The lines you are referring to are the following.
```
// HasTable determines whether the engine has a table with the given name
// in the currently loaded database.
func (e Engine) HasTable(name string) bool {
	ok, err := e.dbfs.HasTable(name)
	return ok && err == nil
}
```
I think there's a bit of diff confusion going on here 😄

File: internal/engine/page_container.go [hunk 12]
```diff
@@ -33,23 +32,25 @@ import (
...
 	return PageContainer{
-		pageID: id,
-		cache:  e.pageCache,
+		pageID:  id,
+		load:    load,
+		release: release,
 	}
 }
 
 // Load loads the page of this page container from the cache. It also pins
```
[the remark this answers is not in the document]
Comment (tsatke) [reply internal/engine/page_container.go:49]: page_containers are not used anymore, removing

File: internal/engine/table.go (hunk 4 above)
Comment (tsatke) [reply internal/engine/table.go:45]: > A relation schema is the logical definition of a table - it defines what the name of the table is, and what the name and type of each column is. It's like a plan or a blueprint. A database schema is the collection of relation schemas for a whole database.

I also don't like the ambiguity. I also thought about putting it into table, but for now I wanna keep it as `schema.Schema`.

File: internal/engine/table.go (hunk 5 above)
Comment (tsatke) [reply internal/engine/table.go:56]: Nope, just an accessor to table files.

File: internal/test/examples_test.go (hunk 7 above)
Comment (tsatke) [reply internal/test/examples_test.go:105]: removed because of the new file system, and TestExample08 relied on an existing database file. I didn't think it was worth porting it, because there will be enough tests that test the new file system.
I added it back then just to see a database file really 😄

Comment (tsatke) [reply internal/test/examples_test.go:105]: I.e. the same functionality should be tested by 06 and/or 07 I think, 08 just relies on everything being in a file

File: internal/engine/engine.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (SUMUKHA-PK) [reply internal/engine/engine.go:85]: Ah cool makes sense

File: internal/engine/table.go (hunk 4 above)
Comment (SUMUKHA-PK) [reply internal/engine/table.go:45]: Sure. Pin this or write something about this as a comment maybe for the future.

File: internal/engine/dbfs/dbfs.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (SUMUKHA-PK) [reply internal/engine/dbfs/dbfs.go:61]: I mean, it can return the loaded tables data. I saw that similar lines were written multiple times...

File: internal/engine/dbfs/dbfs.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (SUMUKHA-PK) [reply internal/engine/dbfs/dbfs.go:93]: Sure alright

File: internal/engine/table.go (hunk 4 above)
Comment (tsatke) [reply internal/engine/table.go:45]: It's in the godoc to the `Schema` struct

File: internal/engine/dbfs/paged_file.go [hunk 13]
```diff
@@ -0,0 +1,134 @@
...
+	_, err := pf.file.WriteAt(data, offset)
+	if err != nil {
+		return fmt.Errorf("write at: %w", err)
+	}
+	return nil
+}
+
+// AllocateNewPage will create a new page in this file.
+func (pf *PagedFile) AllocateNewPage() (*page.Page, error) {
+	newID := pf.highestPageID + 1
```
[the remark this answers is not in the document]
Comment (tsatke) [reply internal/engine/dbfs/paged_file.go:112]: added comments

**Comment by tsatke** [comment]
> Good start! Some questions and documentation needs are expressed. Maybe also add some sort of doc to the `xdbdoc` repo if this is concrete.

Definetly, but for now, this is just a skeleton, slow AF, inserts not working etc
Wanna optimize it before uploading the concept behind it

**Review by SUMUKHA-PK — APPROVED** [review]
:)
